[package]
name = "variables"
version = "0.1.0"
edition.workspace = true
author.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
